baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Cloud Fundis'

theme = 'cloudfundis-theme'

disableKinds = ['taxonomy']

[[menu.main]]
name = 'Services'
url = '/services/'
weight = 1
[[menu.main]]
name = 'Work'
url = '/work/'
weight = 2
[[menu.main]]
name = 'Team'
url = '/team/'
weight = 3
[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 4
[[menu.main]]
name = 'Contact'
url = '/contact/'
weight = 5
[[menu.main]]
name = 'Support'
url = '/support/'
weight = 6
