baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Cloud Fundis'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

[pagination]
disableAliases = false
pagerSize = 5
path = 'page'
